#pragma once
// ============================================================
// GuestLogin.h - Guest Login Lua Script Loader
// Writes GuestLogin_BGMI.lua to game data folder
// The game's Lua VM loads it from there
// ============================================================

#include <fstream>
#include <sys/stat.h>

#define GUEST_LOGIN_PATH "/sdcard/Android/data/com.pubg.imobile/files/guest_login.lua"

static const char* g_GuestLoginLua = 
"local function ZxRLog(msg)\n"
"    pcall(print, \"[ZxR] \" .. tostring(msg))\n"
"end\n"
"\n"
"_G.ZxRLog = ZxRLog\n"
"ZxRLog(\"guest chunk _G=\" .. tostring(_G))\n"
"\n"
"local function _zxr_append_native_log(msg)\n"
"    local logs = rawget(_G, \"__ZxR_CPP_LOGS\")\n"
"\n"
"    if type(logs) ~= \"table\" then\n"
"        logs = {}\n"
"        _G.__ZxR_CPP_LOGS = logs\n"
"    end\n"
"\n"
"    logs[#logs + 1] =\n"
"        \"[\" .. tostring(os.time() or 0) .. \"] \" .. tostring(msg)\n"
"\n"
"    if #logs > 128 then\n"
"        table.remove(logs, 1)\n"
"    end\n"
"\n"
"    _G.__ZxR_CPP_LOG_COUNT = #logs\n"
"    return true\n"
"end\n"
"\n"
"_G.__ZxR_GUEST_SCRIPT_LOADED = true\n"
"ZxRLog(\"guest loaded flag set: \" .. tostring(rawget(_G, \"__ZxR_GUEST_SCRIPT_LOADED\")))\n"
"\n"
"-- =========================\n"
"-- Internal Config Flush\n"
"-- =========================\n"
"local function ZxR_FlushConfigNow()\n"
"    local cfg = rawget(_G, \"ZxR_ConfigState\")\n"
"\n"
"    if type(cfg) ~= \"table\" then\n"
"        return false\n"
"    end\n"
"\n"
"    local ok, encoded = pcall(function()\n"
"        if type(json) == \"table\" and json.encode then\n"
"            return json.encode(cfg)\n"
"        end\n"
"\n"
"        local parts = {}\n"
"\n"
"        for k, v in pairs(cfg) do\n"
"            parts[#parts + 1] =\n"
"                tostring(k) .. \"=\" .. tostring(v)\n"
"        end\n"
"\n"
"        return table.concat(parts, \";\")\n"
"    end)\n"
"\n"
"    if ok then\n"
"        _G.__ZxR_LastConfigDump = encoded\n"
"        ZxRLog(\"Config flushed\")\n"
"        return true\n"
"    end\n"
"\n"
"    ZxRLog(\"Config flush failed\")\n"
"    return false\n"
"end\n"
"\n"
"_G.ZxR_FlushConfigNow = ZxR_FlushConfigNow\n"
"\n"
"-- =========================================================\n"
"\n"
"_zxr_append_native_log(\"guest script loaded\")\n"
"\n"
"local function _zxr_guest_log(msg)\n"
"    _zxr_append_native_log(msg)\n"
"    local logger = rawget(_G, \"ZxRLog\")\n"
"\n"
"    if type(logger) == \"function\" then\n"
"        pcall(logger, \"[GuestLogin] \" .. tostring(msg))\n"
"        return\n"
"    end\n"
"\n"
"    pcall(print, \"[ZxR][GuestLogin] \" .. tostring(msg))\n"
"end\n"
"\n"
"local function _zxr_seed_guest_random()\n"
"    if rawget(_G, \"__ZxR_GuestRandomSeeded\") == true then\n"
"        return\n"
"    end\n"
"\n"
"    local seed = os.time() or 1\n"
"    local clock = os.clock and os.clock() or 0\n"
"\n"
"    math.randomseed(seed + math.floor(clock * 100000))\n"
"\n"
"    _G.__ZxR_GuestRandomSeeded = true\n"
"end\n"
"\n"
"local function _zxr_get_guest_channel_value()\n"
"    local shareSource = rawget(_G, \"ShareSource\")\n"
"\n"
"    if type(shareSource) == \"table\"\n"
"        and shareSource.Guest ~= nil then\n"
"        return shareSource.Guest\n"
"    end\n"
"\n"
"    return \"guest\"\n"
"end\n"
"\n"
"local function _zxr_get_guest_imsdk_channel()\n"
"    local channel = rawget(_G, \"BP_ENUM_IMSDK_CHANNEL_GUEST\")\n"
"\n"
"    if type(channel) == \"number\" then\n"
"        return channel\n"
"    end\n"
"\n"
"    return nil\n"
"end\n"
"\n"
"local function _zxr_is_guest_login_type(loginType)\n"
"    local shareSource = rawget(_G, \"ShareSource\")\n"
"\n"
"    if type(shareSource) == \"table\"\n"
"        and shareSource.Guest ~= nil\n"
"        and loginType == shareSource.Guest then\n"
"        return true\n"
"    end\n"
"\n"
"    return loginType == _zxr_get_guest_channel_value()\n"
"end\n"
"\n"
"local function _zxr_is_guest_imsdk_channel(channelId)\n"
"    local guestChannel = _zxr_get_guest_imsdk_channel()\n"
"\n"
"    return type(channelId) == \"number\"\n"
"        and type(guestChannel) == \"number\"\n"
"        and channelId == guestChannel\n"
"end\n"
"\n"
"local function _zxr_table_contains(list, value)\n"
"    if type(list) ~= \"table\" then\n"
"        return false\n"
"    end\n"
"\n"
"    for _, currentValue in ipairs(list) do\n"
"        if currentValue == value then\n"
"            return true\n"
"        end\n"
"    end\n"
"\n"
"    return false\n"
"end\n"
"\n"
"local function _zxr_ensure_guest_channel_list(list)\n"
"    local guestChannel = _zxr_get_guest_channel_value()\n"
"\n"
"    if type(list) ~= \"table\" then\n"
"        list = {}\n"
"    end\n"
"\n"
"    if not _zxr_table_contains(list, guestChannel) then\n"
"        list[#list + 1] = guestChannel\n"
"        _zxr_guest_log(\"Injected guest channel into login list\")\n"
"    end\n"
"\n"
"    return list\n"
"end\n"
"\n"
"local function _zxr_generate_guest_name()\n"
"    _zxr_seed_guest_random()\n"
"\n"
"    local prefix = \"HyperX_\"\n"
"    local charset = \"ABCDEFGHJKLMNPQRSTUVWXYZ23456789\"\n"
"\n"
"    local suffix = {}\n"
"\n"
"    for index = 1, 6 do\n"
"        local randomIndex = math.random(1, #charset)\n"
"\n"
"        suffix[#suffix + 1] =\n"
"            charset:sub(randomIndex, randomIndex)\n"
"    end\n"
"\n"
"    local generatedName =\n"
"        prefix .. table.concat(suffix)\n"
"\n"
"    if #generatedName > 14 then\n"
"        generatedName = generatedName:sub(1, 14)\n"
"    end\n"
"\n"
"    _G.ZxR_GuestGeneratedName = generatedName\n"
"\n"
"    return generatedName\n"
"end\n"
"\n"
"local function _zxr_consume_guest_reset_flag(reason)\n"
"    local cfg = rawget(_G, \"ZxR_ConfigState\")\n"
"\n"
"    if type(cfg) == \"table\" then\n"
"        cfg.guestReset = false\n"
"    end\n"
"\n"
"    _G.ZxR_GuestResetRequested = false\n"
"\n"
"    if type(rawget(_G, \"MarkConfigDirty\")) == \"function\" then\n"
"        pcall(_G.MarkConfigDirty)\n"
"    end\n"
"\n"
"    if type(rawget(_G, \"ZxR_FlushConfigNow\")) == \"function\" then\n"
"        pcall(_G.ZxR_FlushConfigNow)\n"
"    end\n"
"\n"
"    _zxr_guest_log(\n"
"        \"Consumed guestReset flag: \"\n"
"        .. tostring(reason or \"guest_login\")\n"
"    )\n"
"end\n"
"\n"
"local function _zxr_prepare_fresh_guest_login()\n"
"    if rawget(_G, \"ZxR_GuestResetRequested\") ~= true then\n"
"        return false\n"
"    end\n"
"\n"
"    _G.__ZxR_GuestResetActiveAttempt = true\n"
"\n"
"    pcall(function()\n"
"        if Client and Client.ClearChannelID then\n"
"            Client.ClearChannelID(NetInterface)\n"
"        end\n"
"    end)\n"
"\n"
"    _zxr_guest_log(\n"
"        \"Requested fresh guest login path\"\n"
"    )\n"
"\n"
"    return true\n"
"end\n"
"\n"
"_G.ZxR_GetGuestGeneratedName = function()\n"
"    local currentName =\n"
"        rawget(_G, \"ZxR_GuestGeneratedName\")\n"
"\n"
"    if type(currentName) == \"string\"\n"
"        and #currentName > 0 then\n"
"        return currentName\n"
"    end\n"
"\n"
"    return _zxr_generate_guest_name()\n"
"end\n"
"\n"
"local function _zxr_mark_guest_auto_name_pending()\n"
"    _G.ZxR_GuestGeneratedName =\n"
"        _zxr_generate_guest_name()\n"
"\n"
"    _G.ZxR_GuestAutoNamePending = true\n"
"\n"
"    _G.ZxR_GuestAutoNameExpireAt =\n"
"        (os.time() or 0) + 120\n"
"\n"
"    _zxr_guest_log(\n"
"        \"Prepared guest auto-name: \"\n"
"        .. tostring(_G.ZxR_GuestGeneratedName)\n"
"    )\n"
"end\n"
"\n"
"local function _zxr_is_guest_auto_name_pending()\n"
"    if rawget(_G, \"ZxR_GuestAutoNamePending\") ~= true then\n"
"        return false\n"
"    end\n"
"\n"
"    local expiresAt =\n"
"        tonumber(\n"
"            rawget(_G, \"ZxR_GuestAutoNameExpireAt\")\n"
"        ) or 0\n"
"\n"
"    local now = os.time() or 0\n"
"\n"
"    if expiresAt > 0 and now > expiresAt then\n"
"        _G.ZxR_GuestAutoNamePending = false\n"
"        _G.ZxR_GuestAutoNameExpireAt = 0\n"
"        return false\n"
"    end\n"
"\n"
"    return true\n"
"end\n"
"\n"
"local function _zxr_patch_login_module_instance(loginModule)\n"
"    if type(loginModule) ~= \"table\" then\n"
"        return false\n"
"    end\n"
"\n"
"    if loginModule.__ZxR_GuestLoginPatched == true then\n"
"        return true\n"
"    end\n"
"\n"
"    if type(loginModule.GetLoginTypeList) ~= \"function\" then\n"
"        return false\n"
"    end\n"
"\n"
"    local originalGetLoginTypeList =\n"
"        loginModule.GetLoginTypeList\n"
"\n"
"    loginModule.GetLoginTypeList =\n"
"        function(self, ...)\n"
"            local result =\n"
"                originalGetLoginTypeList(self, ...)\n"
"\n"
"            return _zxr_ensure_guest_channel_list(result)\n"
"        end\n"
"\n"
"    loginModule.__ZxR_GuestLoginPatched = true\n"
"\n"
"    _zxr_guest_log(\n"
"        \"Patched login_module:GetLoginTypeList\"\n"
"    )\n"
"\n"
"    return true\n"
"end\n"
"\n"
"local function _zxr_try_patch_login_module()\n"
"    local okMM, ModuleManager =\n"
"        pcall(\n"
"            require,\n"
"            \"client.module_framework.ModuleManager\"\n"
"        )\n"
"\n"
"    if not okMM\n"
"        or not ModuleManager\n"
"        or not ModuleManager.GetModule\n"
"        or not ModuleManager.LobbyModuleConfig then\n"
"        return false\n"
"    end\n"
"\n"
"    local okModule, loginModule =\n"
"        pcall(function()\n"
"            return ModuleManager.GetModule(\n"
"                ModuleManager.LobbyModuleConfig.login_module\n"
"            )\n"
"        end)\n"
"\n"
"    if okModule and loginModule then\n"
"        return _zxr_patch_login_module_instance(loginModule)\n"
"    end\n"
"\n"
"    return false\n"
"end\n"
"\n"
"local function _zxr_try_patch_login_ui_direct()\n"
"    local okUI, LoginUI =\n"
"        pcall(\n"
"            require,\n"
"            \"client.slua.umg.NewLogin.Login_UIBP\"\n"
"        )\n"
"\n"
"    if okUI and LoginUI then\n"
"        return _zxr_patch_login_ui_module(LoginUI)\n"
"    end\n"
"\n"
"    return false\n"
"end\n"
"\n"
"local function _zxr_patch_login_ui_module(mod)\n"
"    if type(mod) ~= \"table\" then\n"
"        return false\n"
"    end\n"
"\n"
"    if mod.__ZxR_GuestLoginUIPatched == true then\n"
"        return true\n"
"    end\n"
"\n"
"    if type(mod.UpdateLoginButtons) ~= \"function\"\n"
"        or type(mod.OnClickLogin) ~= \"function\" then\n"
"        return false\n"
"    end\n"
"\n"
"    local originalUpdateLoginButtons =\n"
"        mod.UpdateLoginButtons\n"
"\n"
"    mod.UpdateLoginButtons =\n"
"        function(self, ...)\n"
"            local result =\n"
"                originalUpdateLoginButtons(self, ...)\n"
"\n"
"            self.loginChannels =\n"
"                _zxr_ensure_guest_channel_list(\n"
"                    self.loginChannels\n"
"                )\n"
"\n"
"            _zxr_guest_log(\"UpdateLoginButtons patched\")\n"
"\n"
"            return result\n"
"        end\n"
"\n"
"    local originalOnClickLogin =\n"
"        mod.OnClickLogin\n"
"\n"
"    mod.OnClickLogin =\n"
"        function(self, ...)\n"
"            local channel = ...\n"
"            if channel == _zxr_get_guest_channel_value() then\n"
"                pcall(_zxr_prepare_fresh_guest_login)\n"
"                _zxr_mark_guest_auto_name_pending()\n"
"                _zxr_guest_log(\"Guest OnClickLogin hit\")\n"
"            end\n"
"\n"
"            return originalOnClickLogin(\n"
"                self,\n"
"                ...\n"
"            )\n"
"        end\n"
"\n"
"    mod.__ZxR_GuestLoginUIPatched = true\n"
"\n"
"    _zxr_guest_log(\n"
"        \"Patched Login_UI guest flow\"\n"
"    )\n"
"\n"
"    return true\n"
"end\n"
"\n"
"local function _zxr_patch_imsdk_interface_module(mod)\n"
"    if type(mod) ~= \"table\" then\n"
"        return false\n"
"    end\n"
"\n"
"    if mod.__ZxR_GuestResetIMSDKPatched == true then\n"
"        return true\n"
"    end\n"
"\n"
"    local patchedAny = false\n"
"\n"
"    if type(mod.Login) == \"function\" then\n"
"        local originalLogin = mod.Login\n"
"\n"
"        mod.Login =\n"
"            function(\n"
"                self,\n"
"                loginType,\n"
"                extraJson,\n"
"                skipLocalCacheCheck\n"
"            )\n"
"\n"
"                if _zxr_is_guest_login_type(loginType)\n"
"                    and rawget(\n"
"                        _G,\n"
"                        \"ZxR_GuestResetRequested\"\n"
"                    ) == true then\n"
"\n"
"                    pcall(\n"
"                        _zxr_prepare_fresh_guest_login\n"
"                    )\n"
"\n"
"                    skipLocalCacheCheck = true\n"
"\n"
"                    _zxr_guest_log(\n"
"                        \"Forced guest login to skip local cache\"\n"
"                    )\n"
"                end\n"
"\n"
"                if _zxr_is_guest_login_type(loginType) then\n"
"                    _zxr_guest_log(\"IMSDK Login guest path\")\n"
"                end\n"
"\n"
"                return originalLogin(\n"
"                    self,\n"
"                    loginType,\n"
"                    extraJson,\n"
"                    skipLocalCacheCheck\n"
"                )\n"
"            end\n"
"\n"
"        patchedAny = true\n"
"    end\n"
"\n"
"    if type(mod.ForbidLoginWithLocalCache)\n"
"        == \"function\" then\n"
"\n"
"        local originalForbid =\n"
"            mod.ForbidLoginWithLocalCache\n"
"\n"
"        mod.ForbidLoginWithLocalCache =\n"
"            function(self, imsdkLoginChannelId, ...)\n"
"\n"
"                if _zxr_is_guest_imsdk_channel(\n"
"                    imsdkLoginChannelId\n"
"                )\n"
"                    and rawget(\n"
"                        _G,\n"
"                        \"ZxR_GuestResetRequested\"\n"
"                    ) == true then\n"
"\n"
"                    _zxr_guest_log(\n"
"                        \"Forbidding guest local-cache login path\"\n"
"                    )\n"
"\n"
"                    return true\n"
"                end\n"
"\n"
"                if _zxr_is_guest_imsdk_channel(imsdkLoginChannelId) then\n"
"                    _zxr_guest_log(\"ForbidLoginWithLocalCache guest path\")\n"
"                end\n"
"\n"
"                return originalForbid(\n"
"                    self,\n"
"                    imsdkLoginChannelId,\n"
"                    ...\n"
"                )\n"
"            end\n"
"\n"
"        patchedAny = true\n"
"    end\n"
"\n"
"    if type(mod.OnMSDKLogin) == \"function\" then\n"
"        local originalOnMSDKLogin =\n"
"            mod.OnMSDKLogin\n"
"\n"
"        mod.OnMSDKLogin =\n"
"            function(self, ...)\n"
"                local result =\n"
"                    originalOnMSDKLogin(self, ...)\n"
"\n"
"                if rawget(\n"
"                    _G,\n"
"                    \"__ZxR_GuestResetActiveAttempt\"\n"
"                ) == true then\n"
"\n"
"                    _G.__ZxR_GuestResetActiveAttempt =\n"
"                        false\n"
"\n"
"                    pcall(\n"
"                        _zxr_consume_guest_reset_flag,\n"
"                        \"imsdk_login_success\"\n"
"                    )\n"
"                end\n"
"\n"
"                return result\n"
"            end\n"
"\n"
"        patchedAny = true\n"
"    end\n"
"\n"
"    if not patchedAny then\n"
"        return false\n"
"    end\n"
"\n"
"    mod.__ZxR_GuestResetIMSDKPatched = true\n"
"\n"
"    _zxr_guest_log(\n"
"        \"Patched IMSDK guest reset flow\"\n"
"    )\n"
"\n"
"    return true\n"
"end\n"
"\n"
"local function _zxr_try_patch_imsdk_interface()\n"
"    local okDirect, direct =\n"
"        pcall(\n"
"            require,\n"
"            \"client.logic.login.logic_imsdk_interface\"\n"
"        )\n"
"\n"
"    if okDirect and direct then\n"
"        return _zxr_patch_imsdk_interface_module(direct)\n"
"    end\n"
"\n"
"    if type(package) ~= \"table\"\n"
"        or type(package.loaded) ~= \"table\" then\n"
"        return false\n"
"    end\n"
"\n"
"    direct =\n"
"        package.loaded[\n"
"            \"client.logic.login.logic_imsdk_interface\"\n"
"        ]\n"
"\n"
"    return _zxr_patch_imsdk_interface_module(direct)\n"
"end\n"
"\n"
"local function _zxr_patch_revise_name_module(mod)\n"
"    if type(mod) ~= \"table\" then\n"
"        return false\n"
"    end\n"
"\n"
"    if mod.__ZxR_GuestRenamePatched == true then\n"
"        return true\n"
"    end\n"
"\n"
"    if type(mod.OnShow) ~= \"function\"\n"
"        or type(mod.RealModifyName) ~= \"function\" then\n"
"        return false\n"
"    end\n"
"\n"
"    local originalOnShow = mod.OnShow\n"
"\n"
"    mod.OnShow =\n"
"        function(self, ...)\n"
"            local result =\n"
"                originalOnShow(self, ...)\n"
"\n"
"            if self\n"
"                and self._modifyType == 0\n"
"                and _zxr_is_guest_auto_name_pending() then\n"
"\n"
"                local generatedName =\n"
"                    _G.ZxR_GetGuestGeneratedName()\n"
"\n"
"                self._roleName = generatedName\n"
"\n"
"                if self.UIRoot\n"
"                    and self.UIRoot.EditableText_0\n"
"                    and self.UIRoot.EditableText_0.SetText then\n"
"\n"
"                    pcall(function()\n"
"                        self.UIRoot.EditableText_0:SetText(\n"
"                            generatedName\n"
"                        )\n"
"                    end)\n"
"                end\n"
"\n"
"                if self._UpdatePanel then\n"
"                    pcall(self._UpdatePanel, self)\n"
"                end\n"
"\n"
"                _G.ZxR_GuestAutoNamePending = false\n"
"                _G.ZxR_GuestAutoNameExpireAt = 0\n"
"\n"
"                _zxr_guest_log(\n"
"                    \"Prefilled guest name: \"\n"
"                    .. tostring(generatedName)\n"
"                )\n"
"            end\n"
"\n"
"            return result\n"
"        end\n"
"\n"
"    mod.__ZxR_GuestRenamePatched = true\n"
"\n"
"    _zxr_guest_log(\n"
"        \"Patched revise_name guest prefill flow\"\n"
"    )\n"
"\n"
"    return true\n"
"end\n"
"\n"
"local function _zxr_try_patch_loaded_revise_name()\n"
"    local okDirect, direct =\n"
"        pcall(\n"
"            require,\n"
"            \"client.slua.umg.WarDrobe.revise_name\"\n"
"        )\n"
"\n"
"    if okDirect and _zxr_patch_revise_name_module(direct) then\n"
"        return true\n"
"    end\n"
"\n"
"    if type(package) ~= \"table\"\n"
"        or type(package.loaded) ~= \"table\" then\n"
"        return false\n"
"    end\n"
"\n"
"    direct = package.loaded[\"revise_name\"]\n"
"\n"
"    if _zxr_patch_revise_name_module(direct) then\n"
"        return true\n"
"    end\n"
"\n"
"    for loadedName, loadedModule\n"
"        in pairs(package.loaded) do\n"
"\n"
"        if type(loadedName) == \"string\"\n"
"            and string.find(\n"
"                loadedName,\n"
"                \"revise_name\",\n"
"                1,\n"
"                true\n"
"            ) then\n"
"\n"
"            if _zxr_patch_revise_name_module(\n"
"                loadedModule\n"
"            ) then\n"
"                return true\n"
"            end\n"
"        end\n"
"    end\n"
"\n"
"    return false\n"
"end\n"
"\n"
"local function _zxr_try_patch_loaded_modules()\n"
"    local patchedAny = false\n"
"\n"
"    if _zxr_try_patch_login_module() then\n"
"        patchedAny = true\n"
"    end\n"
"\n"
"    if _zxr_try_patch_login_ui_direct() then\n"
"        patchedAny = true\n"
"    end\n"
"\n"
"    if _zxr_try_patch_loaded_revise_name() then\n"
"        patchedAny = true\n"
"    end\n"
"\n"
"    if _zxr_try_patch_imsdk_interface() then\n"
"        patchedAny = true\n"
"    end\n"
"\n"
"    if patchedAny then\n"
"        _zxr_guest_log(\"Guest hooks installed\")\n"
"    end\n"
"\n"
"    return patchedAny\n"
"end\n"
"\n"
"_G.ZxR_TryInstallGuestLoginHooks =\n"
"    function()\n"
"        return _zxr_try_patch_loaded_modules()\n"
"    end\n"
"\n"
"pcall(function()\n"
"    local okTicker, ticker =\n"
"        pcall(require, \"common.time_ticker\")\n"
"\n"
"    if okTicker\n"
"        and ticker\n"
"        and ticker.AddTimerLoop then\n"
"\n"
"        ticker.AddTimerLoop(\n"
"            0,\n"
"            function()\n"
"                pcall(_zxr_try_patch_loaded_modules)\n"
"            end,\n"
"            -1,\n"
"            1.0\n"
"        )\n"
"    else\n"
"        pcall(_zxr_try_patch_loaded_modules)\n"
"    end\n"
"end)";

void initGuestLogin() {
    if (!g_Settings.bGuestLogin) {
        logStatus("[DISABLED] Guest Login skipped by settings");
        LOGI("[@OWNERHUBEE] Guest Login disabled in settings");
        return;
    }
    
    logStatus("\n=== GUEST LOGIN INIT ===");
    
    // Ensure directory exists
    mkdir("/sdcard/Android/data/com.pubg.imobile/files", 0777);
    
    // Write lua script to file
    FILE* f = fopen(GUEST_LOGIN_PATH, "w");
    if (!f) {
        logStatus("[ERROR] Failed to write guest_login.lua");
        LOGE("[@OWNERHUBEE] Failed to write guest login lua to %s", GUEST_LOGIN_PATH);
        return;
    }
    
    fprintf(f, "%s", g_GuestLoginLua);
    fclose(f);
    chmod(GUEST_LOGIN_PATH, 0666);
    
    logStatus("[OK] Guest login script written to: %s", GUEST_LOGIN_PATH);
    LOGI("[@OWNERHUBEE] Guest login script deployed to %s", GUEST_LOGIN_PATH);
}
