#pragma once
// ============================================================
// LuaSettingsMenu.h - In-Game Settings Menu via Lua Injection
// Deploys settings Lua to game data folder
// Settings are editable via config file AND in-game hooks
// ============================================================

#include <fstream>
#include <sys/stat.h>

#define SETTINGS_LUA_PATH "/sdcard/Android/data/com.pubg.imobile/files/mod_settings_menu.lua"

static const char* g_SettingsMenuLua = 
"-- ============================================================\n"
"-- ZxR Mod Settings Menu - Injected into BGMI Settings UI\n"
"-- Hooks into the game's existing Lua settings framework\n"
"-- ============================================================\n"
"\n"
"local function ZxR_SettingsLog(msg)\n"
"    pcall(print, \"[ZxR][Settings] \" .. tostring(msg))\n"
"end\n"
"\n"
"-- Config path (same as C++ side reads)\n"
"local CONFIG_PATH = \"/sdcard/Android/data/com.pubg.imobile/files/mod_settings.cfg\"\n"
"\n"
"-- Current settings state\n"
"_G.ZxR_ModSettings = _G.ZxR_ModSettings or {\n"
"    AntiCheatBypass = true,\n"
"    AnogsPatches = true,\n"
"    HdmpvePatches = true,\n"
"    HdmpvecorePatches = true,\n"
"    TDataMasterPatches = true,\n"
"    SignerPatches = true,\n"
"    UE4ACPatches = true,\n"
"    SkinChanger = true,\n"
"    FPSUnlock = true,\n"
"    NoRecoil = false,\n"
"    NoShake = false,\n"
"    NoGrass = false,\n"
"    FlashSpeed = false,\n"
"    AimAssist = false,\n"
"    HDRUnlock = true,\n"
"    IPadFOV = false,\n"
"    GuestLogin = true,\n"
"    VerboseLog = false,\n"
"}\n"
"\n"
"-- Read config file\n"
"local function ZxR_ReadConfig()\n"
"    local f = io.open(CONFIG_PATH, \"r\")\n"
"    if not f then\n"
"        ZxR_SettingsLog(\"No config file found, using defaults\")\n"
"        return\n"
"    end\n"
"    \n"
"    for line in f:lines() do\n"
"        if line:sub(1,1) ~= \"#\" and line:sub(1,1) ~= \"[\" and line ~= \"\" then\n"
"            local key, val = line:match(\"^(%w+)=(%d+)\")\n"
"            if key and val then\n"
"                _G.ZxR_ModSettings[key] = (val == \"1\")\n"
"            end\n"
"        end\n"
"    end\n"
"    f:close()\n"
"    ZxR_SettingsLog(\"Config loaded from: \" .. CONFIG_PATH)\n"
"end\n"
"\n"
"-- Write config file\n"
"local function ZxR_WriteConfig()\n"
"    local f = io.open(CONFIG_PATH, \"w\")\n"
"    if not f then\n"
"        ZxR_SettingsLog(\"ERROR: Cannot write config file\")\n"
"        return false\n"
"    end\n"
"    \n"
"    f:write(\"# ========================================\\n\")\n"
"    f:write(\"# BGMI Mod Settings - Edit to toggle features\\n\")\n"
"    f:write(\"# 1 = ON, 0 = OFF\\n\")\n"
"    f:write(\"# Changes take effect on next game restart\\n\")\n"
"    f:write(\"# ========================================\\n\\n\")\n"
"    \n"
"    f:write(\"[AntiCheat]\\n\")\n"
"    f:write(\"AntiCheatBypass=\" .. (_G.ZxR_ModSettings.AntiCheatBypass and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"AnogsPatches=\" .. (_G.ZxR_ModSettings.AnogsPatches and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"HdmpvePatches=\" .. (_G.ZxR_ModSettings.HdmpvePatches and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"HdmpvecorePatches=\" .. (_G.ZxR_ModSettings.HdmpvecorePatches and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"TDataMasterPatches=\" .. (_G.ZxR_ModSettings.TDataMasterPatches and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"SignerPatches=\" .. (_G.ZxR_ModSettings.SignerPatches and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"UE4ACPatches=\" .. (_G.ZxR_ModSettings.UE4ACPatches and \"1\" or \"0\") .. \"\\n\\n\")\n"
"    \n"
"    f:write(\"[GameFeatures]\\n\")\n"
"    f:write(\"SkinChanger=\" .. (_G.ZxR_ModSettings.SkinChanger and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"FPSUnlock=\" .. (_G.ZxR_ModSettings.FPSUnlock and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"NoRecoil=\" .. (_G.ZxR_ModSettings.NoRecoil and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"NoShake=\" .. (_G.ZxR_ModSettings.NoShake and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"NoGrass=\" .. (_G.ZxR_ModSettings.NoGrass and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"FlashSpeed=\" .. (_G.ZxR_ModSettings.FlashSpeed and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"AimAssist=\" .. (_G.ZxR_ModSettings.AimAssist and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"HDRUnlock=\" .. (_G.ZxR_ModSettings.HDRUnlock and \"1\" or \"0\") .. \"\\n\")\n"
"    f:write(\"IPadFOV=\" .. (_G.ZxR_ModSettings.IPadFOV and \"1\" or \"0\") .. \"\\n\\n\")\n"
"    \n"
"    f:write(\"[Lua]\\n\")\n"
"    f:write(\"GuestLogin=\" .. (_G.ZxR_ModSettings.GuestLogin and \"1\" or \"0\") .. \"\\n\\n\")\n"
"    \n"
"    f:write(\"[Debug]\\n\")\n"
"    f:write(\"VerboseLog=\" .. (_G.ZxR_ModSettings.VerboseLog and \"1\" or \"0\") .. \"\\n\")\n"
"    \n"
"    f:close()\n"
"    ZxR_SettingsLog(\"Config saved to: \" .. CONFIG_PATH)\n"
"    return true\n"
"end\n"
"\n"
"-- Toggle a setting\n"
"_G.ZxR_ToggleSetting = function(key)\n"
"    if _G.ZxR_ModSettings[key] ~= nil then\n"
"        _G.ZxR_ModSettings[key] = not _G.ZxR_ModSettings[key]\n"
"        ZxR_WriteConfig()\n"
"        ZxR_SettingsLog(\"Toggled \" .. key .. \" = \" .. tostring(_G.ZxR_ModSettings[key]))\n"
"        return true\n"
"    end\n"
"    return false\n"
"end\n"
"\n"
"-- Get all settings as formatted string (for display)\n"
"_G.ZxR_GetSettingsDisplay = function()\n"
"    local lines = {}\n"
"    lines[#lines+1] = \"=== ZxR MOD SETTINGS ===\"\n"
"    lines[#lines+1] = \"\"\n"
"    lines[#lines+1] = \"[Anti-Cheat Bypass]\"\n"
"    lines[#lines+1] = \"  AntiCheatBypass: \" .. (_G.ZxR_ModSettings.AntiCheatBypass and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  AnogsPatches: \" .. (_G.ZxR_ModSettings.AnogsPatches and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  HdmpvePatches: \" .. (_G.ZxR_ModSettings.HdmpvePatches and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  TDataMaster: \" .. (_G.ZxR_ModSettings.TDataMasterPatches and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  UE4 AC: \" .. (_G.ZxR_ModSettings.UE4ACPatches and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"\"\n"
"    lines[#lines+1] = \"[Game Features]\"\n"
"    lines[#lines+1] = \"  SkinChanger: \" .. (_G.ZxR_ModSettings.SkinChanger and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  FPSUnlock: \" .. (_G.ZxR_ModSettings.FPSUnlock and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  NoRecoil: \" .. (_G.ZxR_ModSettings.NoRecoil and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  NoShake: \" .. (_G.ZxR_ModSettings.NoShake and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  NoGrass: \" .. (_G.ZxR_ModSettings.NoGrass and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  HDRUnlock: \" .. (_G.ZxR_ModSettings.HDRUnlock and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"  IPadFOV: \" .. (_G.ZxR_ModSettings.IPadFOV and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"\"\n"
"    lines[#lines+1] = \"[Other]\"\n"
"    lines[#lines+1] = \"  GuestLogin: \" .. (_G.ZxR_ModSettings.GuestLogin and \"ON\" or \"OFF\")\n"
"    lines[#lines+1] = \"\"\n"
"    lines[#lines+1] = \"Edit: \" .. CONFIG_PATH\n"
"    return table.concat(lines, \"\\n\")\n"
"end\n"
"\n"
"-- Hook into game settings UI (patch Setting_Basic_Child)\n"
"local function ZxR_TryPatchSettingsUI()\n"
"    -- Try to hook into the game's settings panel\n"
"    local okBasic, BasicChild = pcall(require, \"client.slua.umg.NewSetting.Basic.Setting_Basic_Child_NewUIBP\")\n"
"    \n"
"    if not okBasic or not BasicChild then\n"
"        -- Try alternative path\n"
"        if type(package) == \"table\" and type(package.loaded) == \"table\" then\n"
"            for name, mod in pairs(package.loaded) do\n"
"                if type(name) == \"string\" and name:find(\"Setting_Basic_Child\") then\n"
"                    BasicChild = mod\n"
"                    break\n"
"                end\n"
"            end\n"
"        end\n"
"    end\n"
"    \n"
"    if not BasicChild or BasicChild.__ZxR_SettingsPatched then\n"
"        return false\n"
"    end\n"
"    \n"
"    -- Patch OnInitialize to add our settings section\n"
"    if type(BasicChild.OnInitialize) == \"function\" then\n"
"        local origInit = BasicChild.OnInitialize\n"
"        BasicChild.OnInitialize = function(self, ...)\n"
"            local result = origInit(self, ...)\n"
"            -- After original init, we can hook into the UI\n"
"            ZxR_SettingsLog(\"Settings UI initialized - mod settings available via config file\")\n"
"            return result\n"
"        end\n"
"    end\n"
"    \n"
"    BasicChild.__ZxR_SettingsPatched = true\n"
"    ZxR_SettingsLog(\"Settings UI patched successfully\")\n"
"    return true\n"
"end\n"
"\n"
"-- Initialize\n"
"ZxR_ReadConfig()\n"
"\n"
"-- Try to patch settings UI with timer\n"
"pcall(function()\n"
"    local okTicker, ticker = pcall(require, \"common.time_ticker\")\n"
"    if okTicker and ticker and ticker.AddTimerLoop then\n"
"        ticker.AddTimerLoop(0, function()\n"
"            pcall(ZxR_TryPatchSettingsUI)\n"
"        end, 5, 2.0) -- Try 5 times, every 2 seconds\n"
"    else\n"
"        pcall(ZxR_TryPatchSettingsUI)\n"
"    end\n"
"end)\n"
"\n"
"ZxR_SettingsLog(\"Mod settings system initialized\")\n"
"_G.__ZxR_SETTINGS_LOADED = true\n"
"\n"
;

void initSettingsMenu() {
    logStatus("\n=== SETTINGS MENU INIT ===");
    
    // Ensure directory exists
    mkdir("/sdcard/Android/data/com.pubg.imobile/files", 0777);
    
    // Write lua settings menu script
    FILE* f = fopen(SETTINGS_LUA_PATH, "w");
    if (!f) {
        logStatus("[ERROR] Failed to write settings menu lua");
        LOGE("[@OWNERHUBEE] Failed to write settings menu lua to %s", SETTINGS_LUA_PATH);
        return;
    }
    
    fprintf(f, "%s", g_SettingsMenuLua);
    fclose(f);
    chmod(SETTINGS_LUA_PATH, 0666);
    
    logStatus("[OK] Settings menu lua written to: %s", SETTINGS_LUA_PATH);
    LOGI("[@OWNERHUBEE] Settings menu deployed to %s", SETTINGS_LUA_PATH);
}
